<template>
  <div class="_content_1mq9d_77" id="account-section">
    <div class="_credits_1mrvx_1 animation fade-in">
      <div class="_section_1mrvx_20 _usage_1mrvx_59">
        <div class="_heading_1mrvx_30">
          <h2>Credit usage</h2>
        </div>

        <div class="_content_1mrvx_44">
          <figure class="_summary_1mrvx_63">
            <div class="_graph_1mrvx_69">
              <div
                class="recharts-responsive-container"
                width="942"
                height="174"
                style="width: 100%; height: 100%; min-width: 0px"
              >
                <div
                  class="recharts-wrapper"
                  role="region"
                  style="
                    position: relative;
                    cursor: default;
                    width: 942px;
                    height: 174px;
                  "
                >
                  <img
                    src="../../assets/account_image/credit_img/credit_usage_img.png"
                    width="942"
                    height="174"
                  />
                  <div></div>
                </div>
              </div>
            </div>
            <figcaption>
              Data as per UTC. Usage means length of content (in minutes)
              generated by Fliki .
            </figcaption>
          </figure>
          <div class="_counter_1mrvx_88">
            <div>
              <div class="_progress_1mrvx_93">
                <div class="_completed_1mrvx_105" style="width: 18%"></div>
              </div>
            </div>
            <p>Credits used: 0.9/5 minutes (18%)</p>
            <p class="_subtext_1mrvx_50">
              (credits will reset on Aug 31, 02:17 pm)
            </p>
            <div style="margin-top: 1rem">
              <button
                class="style-module_button__-niPX style-module_outline__Yyq-Q style-module_small__8crLq"
              >
                <span>
                  <span>🎥 Video - How credits work</span>
                </span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="_section_1mrvx_20 _plan_1mrvx_123">
        <div class="_heading_1mrvx_30">
            <h2>Plan</h2>
        </div>

        <div class="_content_1mrvx_44">
            <p class="_plan_1mrvx_123">Free</p>
            <p class="_subtext_1mrvx_50">
                (active since Jul 31, 2023)
            </p>
            <div id="payment-section" class="_upgrade_1mrvx_146">
                <p>
                    <button class="style-module_button__-niPX style-module_primary__FOp7N style-module_medium__ASKee">
                        <span>
                            <span>
                                <img src="../../assets/account_image/credit_img/blink_img.png" width="16" height="16" alt="image">
                                <span class="style-module_spacing__fGq8-"></span>
                            </span>
                            <span>Subscribe to Fliki</span>
                        </span>
                    </button>
                </p>
            </div>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped>
._account_1mq9d_1 ._content_1mq9d_77 {
  display: flex;
  flex-direction: column;
  flex: 1;
  flex-shrink: 0;
  overflow-x: auto;
  /* overflow-y: scroll; */
  margin-left: 1.5rem;
}

.animation {
  transform: translateZ(0);
  will-change: transform;
}
._credits_1mrvx_1 {
  display: flex;
  flex-direction: column;
  flex: 1;
  flex-shrink: 0;
}

.animation.fade-in {
  animation-name: fadein;
  animation-duration: 0.5s;
  animation-fill-mode: forwards;
  opacity: 0;
}

@keyframes fadein {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
._credits_1mrvx_1 ._section_1mrvx_20 {
    display: flex;
    flex-direction: column;
    max-width: 60rem;
    color: hsl(0, 0%, 9%);
}
._credits_1mrvx_1 ._section_1mrvx_20 ._heading_1mrvx_30 {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
}
h1, h2, h3, h4, h5, h6, p, a, ul, li, label, input, textarea, select {
    margin: 0;
    padding: 0;
}
._credits_1mrvx_1 ._section_1mrvx_20 ._heading_1mrvx_30 h2 {
    font-weight: 700;
    font-size: 1.125rem;
    color: hsl(0, 0%, 9%);
}
._credits_1mrvx_1 ._section_1mrvx_20 ._content_1mrvx_44 {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    margin-top: .5rem;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._summary_1mrvx_63 {
    display: flex;
    flex-direction: column;
    padding: 0;
    margin: 0;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._summary_1mrvx_63 ._graph_1mrvx_69 {
    display: flex;
    flex-shrink: 0;
    width: 100%;
    height: 12rem;
    font-size: .85rem;
    background-color: hsl(0, 0%, 99%);
    border: 1px solid hsl(0, 0%, 90.9%);
    padding: 1rem 1rem 0 0;
    border-radius: .75rem;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._summary_1mrvx_63 figcaption {
    color: hsl(0, 0%, 52.3%);
    margin-top: .5rem;
    font-size: .75rem;
    font-style: italic;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._counter_1mrvx_88 {
    display: flex;
    flex-direction: column;
    margin-top: 1rem;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._counter_1mrvx_88 ._progress_1mrvx_93 {
    display: flex;
    flex: 1;
    flex-shrink: 0;
    height: 1rem;
    width: 100%;
    background-color: hsl(0, 0%, 88.7%);
    border-radius: .5rem;
    position: relative;
    overflow: hidden;
    margin-bottom: .5rem;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._counter_1mrvx_88 ._progress_1mrvx_93 ._completed_1mrvx_105 {
    position: absolute;
    height: 1rem;
    background-color: hsl(190, 95%, 39%);
    transition: width .2s;
}
._credits_1mrvx_1 ._section_1mrvx_20 ._content_1mrvx_44 ._subtext_1mrvx_50 {
    opacity: .75;
}
._credits_1mrvx_1 ._section_1mrvx_20._usage_1mrvx_59 ._counter_1mrvx_88 p {
    font-size: 1rem;
    margin-bottom: .5rem;
}
.style-module_button__-niPX.style-module_small__8crLq {
    height: 1.75rem;
    padding: 0 .75rem;
    border-radius: 1rem;
    font-size: .85rem;
}
.style-module_button__-niPX.style-module_outline__Yyq-Q {
    color: hsl(0, 0%, 43.5%);
    border: 1px solid hsl(0, 0%, 78%);
}
.style-module_button__-niPX span {
    display: flex;
    flex-direction: row;
    align-items: center;
}
._credits_1mrvx_1 ._section_1mrvx_20 {
    display: flex;
    flex-direction: column;
    max-width: 60rem;
    color: hsl(0, 0%, 9%);
}
._credits_1mrvx_1 ._section_1mrvx_20._plan_1mrvx_123 {
    margin-top: 2rem;
    padding-bottom: 2rem;
}
._credits_1mrvx_1 ._section_1mrvx_20 ._heading_1mrvx_30 {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
}
._credits_1mrvx_1 ._section_1mrvx_20 ._heading_1mrvx_30 h2 {
    font-weight: 700;
    font-size: 1.125rem;
    color: hsl(0, 0%, 9%);
}
._credits_1mrvx_1 ._section_1mrvx_20 ._content_1mrvx_44 {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    margin-top: .5rem;
}
._credits_1mrvx_1 ._section_1mrvx_20 ._content_1mrvx_44 ._subtext_1mrvx_50 {
    opacity: .75;
}
._credits_1mrvx_1 ._section_1mrvx_20._plan_1mrvx_123 ._upgrade_1mrvx_146 {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    flex-shrink: 0;
    margin-top: 1rem;
}
</style>
