<template>
  <div id="root">
    <div class="_pages_jouiz_1">
      <header class="_header_1hgra_1">
        <nav>
          <div class="_left_1hgra_13">
            <a href="/">
              <img
                class="logo_login"
                src="../assets//logo_login/logo.png"
                width="20"
                height="20"
              />
              Fliki
            </a>
          </div>
          <div class="_right_1hgra_18">
            <a href="#">
              <i class="fas fa-user"></i>
              Account
            </a>
            <button type="button">
              <!-- <i class="fas fa-sun"></i> -->
              <img src="../assets/login_image/sun.png" class="fa-sun" width="18" height="18" alt="sun"/>
            </button>
            <div id="radix-:r0:">
              <button>
                <i class="far fa-question-circle"></i>
              </button>
            </div>
          </div>
        </nav>
      </header>
      <div class="_auth_u1fl5_1">
        <div class="_left_u1fl5_8">
          <div class="_heading_u1fl5_20 animation slide-up">
            <h1>Hello 👋</h1>
            <p>Please login or create your Fliki account</p>
          </div>
          <div class="_form_u1fl5_61 animation fade-in delay">
            <div class="_options_u1fl5_66">
              <button
                class="style-module_button__-niPX style-module_secondary__K8Xdw style-module_medium__ASKee"
                type="button"
              >
                <img src="../assets/login_image/google.svg" alt="google" />
                <span class="style-module_spacing__fGq8-"></span>
                Continue with Google
              </button>
              <button
                class="style-module_button__-niPX style-module_secondary__K8Xdw style-module_medium__ASKee"
                type="button"
              >
                <img src="../assets/login_image/facebook.svg" alt="Facebook" />
                <span class="style-module_spacing__fGq8-"></span>
                Continue with Facebook
              </button>
              <button
                class="style-module_button__-niPX style-module_secondary__K8Xdw style-module_medium__ASKee"
                type="button"
              >
                <img src="../assets/login_image/linkedin.svg" alt="LinkedIn" />
                <span class="style-module_spacing__fGq8-"></span>
                Continue with LinkedIn
              </button>
              <div class="_email_1v2hj_1">
                  <button
                    class="style-module_button__-niPX style-module_secondary__K8Xdw style-module_medium__ASKee"
                    type="button"
                  >
                  <router-link :to="{name: 'file_home'}">
                    <i class="fas fa-envelope"></i>
                    <span class="style-module_spacing__fGq8-"></span>
                    Continue with Email
                  </router-link>
                  </button>
              </div>
            </div>
            <p class="_disclaimer_u1fl5_84 animation slide-in delay">
              By signing up you accept Fliki 's
              <a href="#">terms & condition</a>
              and
              <a href="#">privacy policy</a>
              and you acknowledge that content is generated by AI and agree to
              use the tool responsibly.
            </p>
          </div>
        </div>
        <div class="_right_u1fl5_96">
          <h1 class="animation fade-in delay">
            Video creation made 10x simpler & faster with AI !
          </h1>
          <div class="_quote_u1fl5_110 animation fade-in delay">
            <img src="../assets/login_image/nicolai.jpg" />
            <div class="_info_u1fl5_122">
              <h2>Excellent Neural Voices + Super Fast App</h2>
              <blockquote class="animation slide-in delay">
                " I love how clean and fast the interface is, using Fliki is
                fast and snappy and the audio is "rendered" incredibly quickly.
                "
              </blockquote>
              <p>— Nicolai Grut</p>
            </div>
          </div>
          <div class="_quote_u1fl5_110 animation fade-in delay">
            <img src="../assets/login_image/lisa.jpg" />
            <div class="_info_u1fl5_122">
              <h2>Hoping for something like this!</h2>
              <blockquote class="animation slide-in delay">
                " I'm having a great experience with Fliki so I was excited
                about this deal. My first project is turning my blog posts into
                videos, and posting on YouTube/TikTok. "
              </blockquote>
              <p>— Lisa Batitto</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
#root,
#__next {
  display: flex;
  flex-direction: row;
  flex: 1 1 ;
  background-color: #F8F8F8
}
._pages_jouiz_1 {
  display: flex;
  flex-direction: column;
  flex: 1;
}
._header_1hgra_1 {
  display: flex;
  flex-direction: column;
  position: relative;
  z-index: 11;
}
._header_1hgra_1 nav {
  display: flex;
  flex-direction: row;
  padding: 0 0.5rem;
  margin-bottom: 0.5rem;
}
._header_1hgra_1 nav ._left_1hgra_13 {
  display: flex;
  flex-direction: row;
  flex: 1;
}
a {
  color: inherit;
  text-decoration: none;
}
h1,
h2,
h3,
h4,
h5,
h6,
p,
a,
ul,
li,
label,
input,
textarea,
select {
  margin: 0;
  padding: 0;
}
._header_1hgra_1 nav ._left_1hgra_13 a,
._header_1hgra_1 nav ._right_1hgra_18 a {
  display: flex;
  flex-direction: row;
  align-items: center;
  color: hsl(0, 0%, 9%);
  padding: 1rem;
  font-size: 1rem;
  font-weight: 600;
  transition: color 0.2s, opacity 0.2s;
  opacity: 0.8;
  outline: none;
}
._header_1hgra_1 nav ._left_1hgra_13 a .logo_login {
  margin-right: 0.25rem;
}
._header_1hgra_1 nav ._right_1hgra_18 {
  display: flex;
  flex-direction: row;
  align-items: center;
}
._header_1hgra_1 nav ._right_1hgra_18 a .fa-user {
  transition: fill 0.2s;
  margin-right: 0.5rem;
  font-size: 16px;
}
._header_1hgra_1 nav ._right_1hgra_18 button {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  text-transform: uppercase;
  cursor: pointer;
  outline: none;
  background: transparent;
  border: none;
  padding: 0.5rem 1rem;
  transition: opacity 0.2s;
  opacity: 0.8;
  height: 3rem;
  color: hsl(0, 0%, 9%);
}

i.fa-question-circle {
  font-size: 16px;
}
._auth_u1fl5_1 {
  display: flex;
  flex-direction: row;
  flex: 1;
  flex-shrink: 0;
  overflow: hidden;
}
._auth_u1fl5_1 ._left_u1fl5_8 {
  display: flex;
  flex-direction: column;
  padding: 1.5rem;
  margin: 0 1.5rem 1rem;
  width: 25rem;
  overflow-x: hidden;
  overflow-y: auto;
  border-radius: 1rem;
  background-color: hsl(0, 0%, 93%);
  border: 1px solid hsl(0, 0%, 88.7%);
}
.animation {
  transform: translateZ(0);
  will-change: transform;
}
.animation.slide-up {
  animation: slideUp 0.5s;
  animation-fill-mode: forwards;
}
._auth_u1fl5_1 ._left_u1fl5_8 ._heading_u1fl5_20 {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}
._auth_u1fl5_1 ._left_u1fl5_8 ._heading_u1fl5_20 h1 {
  font-weight: 600;
  font-size: 1.875rem;
}
._auth_u1fl5_1 ._left_u1fl5_8 ._heading_u1fl5_20 p {
  color: hsl(0, 0%, 43.5%);
  margin-top: 0.5rem;
}
._auth_u1fl5_1 ._left_u1fl5_8 ._form_u1fl5_61 {
  display: flex;
  flex-direction: column;
  margin-top: 1rem;
}
.animation.delay {
  animation-delay: 0.5s;
}
.animation.fade-in {
  animation-name: fadein;
  animation-duration: 0.5s;
  animation-fill-mode: forwards;
  opacity: 0;
}
.animation {
  transform: translateZ(0);
  will-change: transform;
}
@keyframes fadein {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
button {
  transition: all 0.1s;
}
.style-module_button__-niPX {
  display: flex;
  flex-direction: row;
  align-items: center;
  background-color: transparent;
  border: 1px solid transparent;
  outline: none;
  cursor: pointer;
  font-weight: 700;
  white-space: pre;
}
.style-module_button__-niPX.style-module_medium__ASKee {
  height: 2.15rem;
  padding: 0 1rem;
  border-radius: 1.75rem;
  font-size: 0.9rem;
}
.style-module_button__-niPX.style-module_secondary__K8Xdw {
  background-color: hsl(0, 0%, 99%);
  color: hsl(0, 0%, 9%);
  border: 1px solid hsl(0, 0%, 56.1%);
}
._auth_u1fl5_1 ._left_u1fl5_8 ._form_u1fl5_61 ._options_u1fl5_66 > button {
  width: 14rem;
  justify-content: flex-start;
  align-items: center;
  margin-top: 1rem;
}

._auth_u1fl5_1
  ._left_u1fl5_8
  ._form_u1fl5_61
  ._options_u1fl5_66
  > button:first-child {
  margin-top: 0;
}
.style-module_button__-niPX.style-module_medium__ASKee svg,
.style-module_button__-niPX.style-module_medium__ASKee img {
  width: 1rem;
  height: 1rem;
}
.style-module_button__-niPX.style-module_medium__ASKee
  .style-module_spacing__fGq8- {
  width: 0.25rem;
}
._email_1v2hj_1 {
  display: flex;
  flex-direction: column;
}
._email_1v2hj_1 > button {
  width: 14rem;
  justify-content: flex-start;
  align-items: center;
  margin-top: 1rem;
}
.animation {
  transform: translateZ(0);
  will-change: transform;
}
.animation.slide-in {
  animation: slideIn 0.5s;
  animation-fill-mode: forwards;
}
.animation.delay {
  animation-delay: 0.5s;
}
._auth_u1fl5_1 ._left_u1fl5_8 ._form_u1fl5_61 ._disclaimer_u1fl5_84 {
  color: hsl(0, 0%, 43.5%);
  font-size: 0.75rem;
  font-style: italic;
  font-weight: 400;
  border-top: 1px solid hsl(0, 0%, 88.7%);
  margin-top: 1rem;
  padding-top: 1rem;
}

@keyframes slideIn {
  0% {
    transform: translate(-0.5rem);
    opacity: 0.1;
  }
  100% {
    transform: translate(0);
    opacity: 1;
  }
}
._auth_u1fl5_1 ._left_u1fl5_8 ._form_u1fl5_61 ._disclaimer_u1fl5_84 a {
  text-decoration: underline;
}
._auth_u1fl5_1 ._right_u1fl5_96 {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  flex: 1;
  padding: 2rem;
  overflow-x: hidden;
  overflow-y: auto;
}
._auth_u1fl5_1 ._right_u1fl5_96 h1 {
  text-align: center;
  font-size: 1.875rem;
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 {
  display: flex;
  flex-direction: row;
  max-width: 40rem;
  margin-top: 2rem;
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 img {
  width: 5rem;
  height: 5rem;
  border-radius: 50%;
  border: 1px solid hsl(0, 0%, 56.1%);
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 ._info_u1fl5_122 {
  display: flex;
  flex-direction: column;
  flex: 1;
  margin-left: 1rem;
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 ._info_u1fl5_122 h2 {
  font-size: 1.125rem;
  margin-bottom: 0.5rem;
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 ._info_u1fl5_122 blockquote {
  font-size: 1rem;
  font-style: italic;
  padding: 0;
  margin: 0;
  color: hsl(0, 0%, 9%);
}
._auth_u1fl5_1 ._right_u1fl5_96 ._quote_u1fl5_110 ._info_u1fl5_122 p {
  font-size: 1rem;
  font-weight: 600;
  color: hsl(0, 0%, 43.5%);
  margin-top: 0.5rem;
}
.style-module_button__-niPX a {
    display: flex;
    flex-direction: row;
    align-items: center;
}
@keyframes slideUp {
  0% {
    transform: translateY(0.5rem);
    opacity: 0.1;
  }
  100% {
    transform: translateY(0);
    opacity: 1;
  }
}
._auth_u1fl5_1 ._right_u1fl5_96 {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex: 1;
    padding: 2rem;
    overflow-x: hidden;
    overflow-y: auto;
}
@media (max-width: 1023px){
  #root {
      flex-direction: column;
  }
  ._auth_u1fl5_1 {
    flex-direction: column;
    overflow: unset;
}
._auth_u1fl5_1 ._left_u1fl5_8 {
    overflow: unset;
    width: auto;
}
._auth_u1fl5_1 ._right_u1fl5_96 {
    overflow: unset;
}
}
</style>
